app:
  baseUrl: https://${CUSTOM_DOMAIN}

organization:
  name: ERNI-Academy

backend:
  baseUrl: https://${CUSTOM_DOMAIN}
  listen:
    port: 80
  cors:
    origin: https://${CUSTOM_DOMAIN}
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl: true

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

auth:
  environment: production
  providers:
    microsoft:
      production:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        additionalScopes:
          - Mail.Send
    github:
      production:
        clientId: ${GITHUB_ORG_OATH_CLIENT_ID}
        clientSecret: ${GITHUB_ORG_OATH_CLIENT_SECRET}
        ssl: true
      development:
        clientId: ${GITHUB_ORG_OATH_CLIENT_ID}
        clientSecret: ${GITHUB_ORG_OATH_CLIENT_SECRET}

techdocs:
  builder: 'external'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: ${TECHDOCS_CONTAINER_NAME}
      credentials:
        accountName: ${TECHDOCS_STORAGE_ACCOUNT}