app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: http://localhost:7007

backend:
  baseUrl: https://${CUSTOM_DOMAIN}
  listen:
    port: 80
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl: true
  cors:
    origin: https://${CUSTOM_DOMAIN}

techdocs:
  builder: 'external'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: ${TECHDOCS_CONTAINER_NAME}
      credentials:
        accountName: ${TECHDOCS_STORAGE_ACCOUNT}

#catalog:
#  # Overrides the default list locations from app-config.yaml as these contain example data.
#  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
#  # on how to get entities into the catalog.
#  locations: []
